#!/bin/sh
# Release script for gerbv
# (C) 2001 Stefan Petersen (spe@stacken.kth.se)
# $Id$

eval "`grep ^VERSION configure.in`"
RELEASE=gerbv-${VERSION}

RESULT=`grep -c :pserver:anonymous@cvs.gerbv.sourceforge.net:[0-9]*/cvsroot/gerbv ${HOME}/.cvspass`

if [[ $RESULT -eq 0 ]] ; then
	echo You must login with anonymous login to get this to work!
	exit;
fi

(cd /tmp ;\
cvs -z3 -d:pserver:anonymous@cvs.gerbv.sourceforge.net:/cvsroot/gerbv export -r RELEASE_0_0_4 -d ${RELEASE} gerbv ; \
(cd ${RELEASE} ; rm -f build_release rebuild_conf ; \
aclocal ; autoheader ; autoconf ; automake --copy --add-missing) ;\
tar cf ${RELEASE}.tar ${RELEASE} ;\
gzip ${RELEASE}.tar )

cp /tmp/${RELEASE}.tar.gz .
rm -rf /tmp/${RELEASE}.tar.gz /tmp/${RELEASE}
