#!/bin/sh
rm -f confdefs.h config.* configure aclocal.m4 stamp-h* install-sh missing mkinstalldirs
rm -rf autom4te.cache
find . -name Makefile -exec rm {} \;
find . -name Makefile.in -exec rm {} \;

aclocal
autoheader
autoconf
automake --copy --add-missing
